name: shell
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.5'
      - run: sudo apt update && sudo apt-get install -y libpcap-dev && go mod tidy && CGO_ENABLED=1 go build -a -o shell_linux_amd64 -ldflags '-extldflags "-static"' ./cmd/shell/cli.go
      - uses: actions/upload-artifact@v2
        with:
          name: shell
          path: shell_linux_amd64
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: shell_linux_amd64